version: '3.8'

services:
  speaker:
    build:
      context: .
      dockerfile: Dockerfile.speaker
      args:
        - DEBUG=${DEBUG:-false}
    image: eir-speaker
    ports:
      - "3000:3000"  # Expose the OpenAI-compatible API
    environment:
      - PORT=3000
      - API_PORT=3000
      - SPEAKER_PORT=8002
      - EXECUTIVE_URL=http://executive:8001
      - CHROMA_URL=http://chroma:8000
      - SPEAKER_MODEL=${SPEAKER_MODEL}
      - SPEAKER_MODEL_KWARGS=${SPEAKER_MODEL_KWARGS}
      - DEFAULT_API_KEY=${DEFAULT_API_KEY}
      - DEBUG=${DEBUG:-false}
    networks:
      - eir_net
    depends_on:
      - executive
      - chroma

  executive:
    build:
      context: .
      dockerfile: Dockerfile.executive
    image: eir-executive
    ports:
      - "8001:8001"  # Expose the Executive API
    environment:
      - PORT=8001
      - EXECUTIVE_PORT=8001
      - EXECUTIVE_MODEL=${EXECUTIVE_MODEL}
      - EXECUTIVE_MODEL_KWARGS=${EXECUTIVE_MODEL_KWARGS}
      - NEO4J_URL=bolt://neo4j:7687  # This is the internal container port, which remains unchanged
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - eir_net
    depends_on:
      neo4j:
        condition: service_healthy

  chroma:
    image: chromadb/chroma
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"  # Chroma API
    networks:
      - eir_net

  neo4j:
    image: neo4j:2025.02.0
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7475:7474"  # HTTP - changed from 7474 to avoid conflicts
      - "7688:7687"  # Bolt - changed from 7687 to avoid conflicts
    volumes:
      - neo4j_data:/data
    networks:
      - eir_net
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  eir_net:
    driver: bridge

volumes:
  neo4j_data:
  chroma_data: