version: '3.8'

services:
  speaker:
    build:
      context: .
      dockerfile: Dockerfile.speaker
      args:
        - DEBUG=${DEBUG:-false}
    image: exlayer-speaker
    ports:
      - "3000:3000"  # Expose the OpenAI-compatible API
    environment:
      - PORT=3000
      - API_PORT=3000
      - SPEAKER_PORT=8002
      - EXECUTIVE_URL=http://executive:8001
      - SPEAKER_MODEL=${SPEAKER_MODEL}
      - SPEAKER_MODEL_KWARGS=${SPEAKER_MODEL_KWARGS}
      - DEFAULT_API_KEY=${DEFAULT_API_KEY}
      - DEBUG=${DEBUG:-false}
    networks:
      - exlayernet
    depends_on:
      - executive

  executive:
    build:
      context: .
      dockerfile: Dockerfile.executive
    image: exlayer-executive
    ports:
      - "8001:8001"  # Expose the Executive API
    environment:
      - PORT=8001
      - EXECUTIVE_PORT=8001
      - EXECUTIVE_MODEL=${EXECUTIVE_MODEL}
      - EXECUTIVE_MODEL_KWARGS=${EXECUTIVE_MODEL_KWARGS}
      - NEO4J_URL=bolt://neo4j:7687  # This is the internal container port, which remains unchanged
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - EMBEDDING_DIMENSION=384  # all-MiniLM-L6-v2 produces 384-dimensional embeddings
      - DEBUG=true  # Enable debug mode for the executive service
    networks:
      - exlayernet
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    image: neo4j:5.26.4  # Updated to a version that supports vector indexes
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=512m
      # Enable vector index support
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*,vectorize.*,vector.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*,vectorize.*,vector.*
    ports:
      - "7475:7474"  # HTTP - changed from 7474 to avoid conflicts
      - "7688:7687"  # Bolt - changed from 7687 to avoid conflicts
    volumes:
      - neo4j_data:/data
    networks:
      - exlayernet
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

networks:
  exlayernet:
    driver: bridge

volumes:
  neo4j_data: